### ISSUE TITLE
Can this be used without plex?

### ISSUE THREAD

**Issue by Yankees4life** [NiNiyas/autoscan#1]
Hello there

I was wondering if there was a way to use this without installing plex. I don't want to run another media server on top of the one I already like to run. 

Thanks

**Comment by NiNiyas** [comment]
Hey, I guess I can add a trigger to disable plex. Are you interested in something like this?

**Comment by Yankees4life** [comment]
> Hey, I guess I can add a trigger to disable plex. Are you interested in something like this?

Yeah. I don't use plex so I would just like to use this for my jellyfin server

**Comment by NiNiyas** [comment]
I have a working draft for this. How are you planning to run this? In docker or in host?

**Comment by Yankees4life** [comment]
On my windows host, yes.

**Comment by NiNiyas** [comment]
Could you give https://github.com/NiNiyas/autoscan/tree/beta a try and report back please?

**Comment by Yankees4life** [comment]
> Could you give https://github.com/NiNiyas/autoscan/tree/beta a try and report back please?

Ok, that didn't work as I'm getting 404 errors when trying to add it to Radarr even tho it looks its running


> C:\Users\Jean\Documents\Projects\autoscan>scan.py server --loglevel=DEBUG
>  2022-06-09 13:02:29,893 -     INFO -    CONFIG [12164]: Using default setting --config=C:\Users\Jean\Documents\Projects\autoscan\config\config.json
>  2022-06-09 13:02:29,894 -     INFO -    CONFIG [12164]: Using default setting --logfile=C:\Users\Jean\Documents\Projects\autoscan\plex_autoscan.log
>  2022-06-09 13:02:29,900 -     INFO -    CONFIG [12164]: Using ARG setting loglevel=DEBUG
>  2022-06-09 13:02:29,901 -     INFO -    CONFIG [12164]: Using default setting --queuefile=C:\Users\Jean\Documents\Projects\autoscan\queue.db
>  2022-06-09 13:02:29,907 -     INFO -    CONFIG [12164]: Using default setting --cachefile=C:\Users\Jean\Documents\Projects\autoscan\cache.db
>  2022-06-09 13:02:29,911 -    DEBUG -    CONFIG [12164]: Upgrading config...
>  2022-06-09 13:02:29,926 -    DEBUG -    CONFIG [12164]: Config was not upgraded as there were no changes to add.
>  2022-06-09 13:02:30,006 -     INFO -    CONFIG [12164]: Using default setting --config=C:\Users\Jean\Documents\Projects\autoscan\config\config.json
>  2022-06-09 13:02:30,009 -     INFO -    CONFIG [12164]: Using default setting --logfile=C:\Users\Jean\Documents\Projects\autoscan\plex_autoscan.log
>  2022-06-09 13:02:30,011 -     INFO -    CONFIG [12164]: Using ARG setting loglevel=DEBUG
>  2022-06-09 13:02:30,027 -     INFO -    CONFIG [12164]: Using default setting --queuefile=C:\Users\Jean\Documents\Projects\autoscan\queue.db
>  2022-06-09 13:02:30,028 -     INFO -    CONFIG [12164]: Using default setting --cachefile=C:\Users\Jean\Documents\Projects\autoscan\cache.db
> 
>     ____  __             ___         __
>    / __ \/ /__  _  __   /   | __  __/ /_____  ______________ _____
>   / /_/ / / _ \| |/_/  / /| |/ / / / __/ __ \/ ___/ ___/ __ `/ __ \
>  / ____/ /  __/>  <   / ___ / /_/ / /_/ /_/ (__  ) /__/ /_/ / / / /
> /_/   /_/\___/_/|_|  /_/  |_\__,_/\__/\____/____/\___/\__,_/_/ /_/
> 
> 
>  2022-06-09 13:02:30,719 -     INFO -  AUTOSCAN [12164]:
> #########################################################################
> # Title:    Plex Autoscan                                               #
> # Author:   l3uddz                                                      #
> # URL:      https://github.com/l3uddz/plex_autoscan                     #
> # --                                                                    #
> #         Part of the Cloudbox project: https://cloudbox.works          #
> #########################################################################
> #                   GNU General Public License v3.0                     #
> #########################################################################
> 
>  2022-06-09 13:02:30,722 -     INFO -  AUTOSCAN [12164]: Starting server: http://0.0.0.0:3467/163f48fd471b4225bf387cb484be51b5
>  * Serving Flask app 'scan' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off

**Comment by NiNiyas** [comment]
This log doesn't show anything. Can you let it run for like a minute or two and try again? Please also post the config file after redacting.

**Comment by Yankees4life** [comment]
And my config

> {
>   "DOCKER_NAME": "plex",
>   "ENABLE_JOE": true,
>   "ENABLE_PLEX": false,
>   "GOOGLE": {
>     "ALLOWED": {
>       "FILE_EXTENSIONS": true,
>       "FILE_EXTENSIONS_LIST": [
>         "webm",
>         "mkv",
>         "flv",
>         "vob",
>         "ogv",
>         "ogg",
>         "drc",
>         "gif",
>         "gifv",
>         "mng",
>         "avi",
>         "mov",
>         "qt",
>         "wmv",
>         "yuv",
>         "rm",
>         "rmvb",
>         "asf",
>         "amv",
>         "mp4",
>         "m4p",
>         "m4v",
>         "mpg",
>         "mp2",
>         "mpeg",
>         "mpe",
>         "mpv",
>         "m2v",
>         "m4v",
>         "svi",
>         "3gp",
>         "3g2",
>         "mxf",
>         "roq",
>         "nsv",
>         "f4v",
>         "f4p",
>         "f4a",
>         "f4b",
>         "mp3",
>         "flac",
>         "ts"
>       ],
>       "FILE_PATHS": [
>         "F:\\tv\\shows\\",
>         "F:\\tv\\anime\\",
>         "F:\\tv\\sports\\",
>         "F:\\movies\\"		
>       ],
>       "MIME_TYPES": true,
>       "MIME_TYPES_LIST": [
>         "video"
>       ]
>     },
>     "CLIENT_ID": "",
>     "CLIENT_SECRET": "",
>     "DISABLE_DISK_FILE_SIZE_CHECK": false,
>     "ENABLED": false,
>     "POLL_INTERVAL": 120,
>     "SHOW_CACHE_LOGS": true,
>     "TEAMDRIVE": false,
>     "TEAMDRIVES": []
>   },
>   "JELLYFIN_EMBY": "jellyfin",
>   "JOE_API_KEY": "xxx",
>   "JOE_HOST": "http://localhost:8096",
>   "PLEX_ANALYZE_DIRECTORY": true,
>   "PLEX_ANALYZE_TYPE": "basic",
>   "PLEX_CHECK_BEFORE_SCAN": false,
>   "PLEX_DATABASE_PATH": "%LOCALAPPDATA%\\Plex Media Server\\Plug-in Support\\Databases\\com.plexapp.plugins.library.db",
>   "PLEX_EMPTY_TRASH": false,
>   "PLEX_EMPTY_TRASH_CONTROL_FILES": [
>     "F:\\mounted.bin"
>   ],
>   "PLEX_EMPTY_TRASH_MAX_FILES": 100,
>   "PLEX_EMPTY_TRASH_ZERO_DELETED": false,
>   "PLEX_FIX_MISMATCHED": false,
>   "PLEX_FIX_MISMATCHED_LANG": "en",
>   "PLEX_LD_LIBRARY_PATH": "%LOCALAPPDATA%\\Plex Media Server",
>   "PLEX_LOCAL_URL": "http://localhost:32400",
>   "PLEX_SCANNER": "%PROGRAMFILES(X86)%\\Plex\\Plex Media Server\\Plex Media Scanner.exe",
>   "PLEX_SUPPORT_DIR": "%LOCALAPPDATA%\\Plex Media Server",
>   "PLEX_TOKEN": "",
>   "PLEX_USER": "plex",
>   "PLEX_WAIT_FOR_EXTERNAL_SCANNERS": true,
>   "RCLONE": {
>     "BINARY": "%ChocolateyInstall%\\bin\\rclone.exe",
>     "CONFIG": "%HOMEDRIVE%%HOMEPATH%\\.config\\rclone\\rclone.conf",
>     "CRYPT_MAPPINGS": {},
>     "RC_CACHE_REFRESH": {
>       "ENABLED": false,
>       "FILE_EXISTS_TO_REMOTE_MAPPINGS": {
>         "F:\\": [
>           "F:\\"
>         ]
>       },
>       "RC_URL": "http://localhost:5572"
>     }
>   },
>   "RUN_COMMAND_AFTER_SCAN": "",
>   "RUN_COMMAND_BEFORE_SCAN": "",
>   "SERVER_ALLOW_MANUAL_SCAN": false,
>   "SERVER_FILE_CHECK_DELAY": 60,
>   "SERVER_FILE_EXIST_PATH_MAPPINGS": {
>     "F:\\": [
>       "F:\\"
>     ]
>   },
>   "SERVER_IGNORE_LIST": [
>     "/.grab/",
>     ".DS_Store",
>     "Thumbs.db"
>   ],
>   "SERVER_IP": "0.0.0.0",
>   "SERVER_MAX_FILE_CHECKS": 10,
>   "SERVER_PASS": "",
>   "SERVER_PATH_MAPPINGS": {
>     "F:\\": [
>       "F:\\"
>     ]
>   },
>   "SERVER_PORT": 3467,
>   "SERVER_SCAN_DELAY": 180,
>   "SERVER_SCAN_FOLDER_ON_FILE_EXISTS_EXHAUSTION": false,
>   "SERVER_SCAN_PRIORITIES": {
>     "0": [
>       "/Movies/"
>     ],
>     "1": [
>       "/Shows/"
>     ],
>     "2": [
>       "/Anime/"
>     ],
>     "3": [
>       "/Sports/"
>     ]	
>   },
>   "SERVER_USE_SQLITE": false,
>   "USE_DOCKER": false,
>   "USE_SUDO": true
> }

**Comment by Yankees4life** [comment]
> This log doesn't show anything. Can you let it run for like a minute or two and try again? Please also post the config file after redacting.

Been running for 10 minutes and thats what all it showed in the logs....

**Comment by NiNiyas** [comment]
I cannot add it to radarr either. I will look into this.

**Comment by NiNiyas** [comment]
Could you try adding actual ip instead of 0.0.0.0? Like 192.168.1.5 ? I just tried it and it seems to work.

**Comment by Yankees4life** [comment]
> Could you try adding actual ip instead of 0.0.0.0? Like 192.168.1.5 ? I just tried it and it seems to work.

Didn't work for me. Still getting 404 errors

**Comment by Yankees4life** [comment]
Wait a minute. I was the using the server port with another app so thats why it didnt work

**Comment by Yankees4life** [comment]
Ok, it seems like I'm still being asked about the plex database file...which is weird since I disabled plex..and I don't have that installed anywhere

>  2022-06-09 15:36:14,110 -    DEBUG -  AUTOSCAN [ 3008]: Client '192.168.1.72' request dump:
> {
>     "eventType": "Manual",
>     "filepath": "F:/tv/shows/The Price Is Right/Season 50/The Price Is Right - 2022-06-08 - Wed, Jun 8, 2022.mkv"
> }
>  2022-06-09 15:36:14,110 -     INFO -  AUTOSCAN [ 3008]: Client '192.168.1.72' made a manual scan request for: 'F:/tv/shows/The Price Is Right/Season 50/The Price Is Right - 2022-06-08 - Wed, Jun 8, 2022.mkv'
>  2022-06-09 15:36:14,115 -    ERROR -     UTILS [ 3008]: Exception while trying to map 'F:/tv/shows/The Price Is Right/Season 50/The Price Is Right - 2022-06-08 - Wed, Jun 8, 2022.mkv' to a Section ID in the Plex DB:
> Traceback (most recent call last):
>   File "C:\Users\Jean\Documents\Projects\autoscan\utils.py", line 25, in get_plex_section
>     with sqlite3.connect(config['PLEX_DATABASE_PATH']) as conn:
> sqlite3.OperationalError: unable to open database file

**Comment by NiNiyas** [comment]
I just pushed a fix which probably will fix this.

**Comment by Yankees4life** [comment]
OK, that worked

**Comment by NiNiyas** [comment]
So it is working now? Properly scanning? Picked up by jellyfin? No problems adding it to arr apps?

**Comment by Yankees4life** [comment]
> So it is working now? Properly scanning? Picked up by jellyfin? No problems adding it to arr apps?

Yeah. Jellyfin is picking up the files and the arrs are communicating well with it

**Comment by NiNiyas** [comment]
Great! So I am closing this issue. If you have any other issues feel free to open a new one.

**Comment by Yankees4life** [comment]
> Great! So I am closing this issue. If you have any other issues feel free to open a new one.

You should probably merge the beta into the master version now thats it working. Just a suggestion

**Comment by pcm1ke** [comment]
Like the OP I’m also trying to use this with jellyfin, however it doesn’t appear to be causing jellyfin to update its library properly. The arrs appear to send /path/to/file.mkv which is then sent to jellyfin, but when that happens nothing is added to the library? I’m running this to accept manual scans as well and when I manually put in just a /path/ and don’t specify the file inside the folder, jellyfin seems to respond right away and add the files under that path to the library. Am I doing something wrong somewhere? Thank you in advance
