### ISSUE TITLE
Service fails to start

### ISSUE THREAD

**Issue by Brandoskey** [NiNiyas/autoscan#5]
I get the following error when trying to run autoscan as a service. I've successfully gotten plex_autoscan running currently so I can't figure out what has changed that would cause this issue.

Dec 16 10:10:38 ubuntu-plex systemd[1]: Started Autoscan.
Dec 16 10:10:38 ubuntu-plex python3[829437]:  2022-12-16 10:10:38,749 -     INFO -    CONFIG [140251957712704]: Using default setting --config=/opt/autoscan/config/config.json
Dec 16 10:10:38 ubuntu-plex python3[829437]:  2022-12-16 10:10:38,749 -     INFO -    CONFIG [140251957712704]: Using default setting --logfile=/opt/autoscan/autoscan.log
Dec 16 10:10:38 ubuntu-plex python3[829437]:  2022-12-16 10:10:38,749 -     INFO -    CONFIG [140251957712704]: Using ARG setting loglevel=INFO
Dec 16 10:10:38 ubuntu-plex python3[829437]:  2022-12-16 10:10:38,749 -     INFO -    CONFIG [140251957712704]: Using default setting --queuefile=/opt/autoscan/queue.db
Dec 16 10:10:38 ubuntu-plex python3[829437]:  2022-12-16 10:10:38,750 -     INFO -    CONFIG [140251957712704]: Using default setting --cachefile=/opt/autoscan/cache.db
Dec 16 10:10:38 ubuntu-plex python3[829437]: Traceback (most recent call last):
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/opt/autoscan/scan.py", line 65, in <module>
Dec 16 10:10:38 ubuntu-plex python3[829437]:     conf.load()
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/opt/autoscan/config.py", line 296, in load
Dec 16 10:10:38 ubuntu-plex python3[829437]:     cfg, upgraded = self.upgrade_settings(json.load(fp))
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/usr/lib/python3.8/json/__init__.py", line 293, in load
Dec 16 10:10:38 ubuntu-plex python3[829437]:     return loads(fp.read(),
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
Dec 16 10:10:38 ubuntu-plex python3[829437]:     return _default_decoder.decode(s)
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
Dec 16 10:10:38 ubuntu-plex python3[829437]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Dec 16 10:10:38 ubuntu-plex python3[829437]:   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
Dec 16 10:10:38 ubuntu-plex python3[829437]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Dec 16 10:10:38 ubuntu-plex python3[829437]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Dec 16 10:10:38 ubuntu-plex systemd[1]: autoscan.service: Main process exited, code=exited, status=1/FAILURE
Dec 16 10:10:38 ubuntu-plex systemd[1]: autoscan.service: Failed with result 'exit-code'.
Dec 16 10:10:49 ubuntu-plex systemd[1]: autoscan.service: Scheduled restart job, restart counter is at 255.
Dec 16 10:10:49 ubuntu-plex systemd[1]: Stopped Autoscan.

**Comment by NiNiyas** [comment]
Could you post your config file please? The above traceback shows that Autoscan is having trouble decoding the config file.

**Comment by Brandoskey** [comment]
No need, your reply prompted me to throw my config for both auto scan and plex_autoscan into a diffchecker to see if there was something I was missing and there in the first line first column was a ' causing me all sorts of grief. No idea how it got in there but all seems to be working now.

Thanks for taking over this project btw!
