### ISSUE TITLE
Lidarr options do not match documentation

### ISSUE THREAD

**Issue by EricH9958** [NiNiyas/autoscan#7]
Looks like Lidarr updated their connect options to match more closely what Sonarr and Radarr are using.  
Not sure which of these I should choose. 

![image](https://github.com/NiNiyas/autoscan/assets/29580743/43fe7c59-c0bf-4b43-9dc0-331f4216c3ae)

**Comment by EricH9958** [comment]
I tested a few options and it looks like On Release Import works. Any of the other options returns an error. 

AUTOSCAN [140260940547648]: Unknown scan request from: '192.168.1.99'

**Comment by NiNiyas** [comment]
Hi. Thanks for opening the issue. Unfortunately, I don't use Lidarr, but I will spin one up in the coming days and look at this. PR's are welcome; also, if you have the webhook payloads for `On Grab` and `On Release Import` events, please post them here.

**Comment by EricH9958** [comment]
Not sure what a PR is.  If you could give me some information on how to get the webhook payloads for those items I would try and get them for you.

**Comment by NiNiyas** [comment]
If you set the `--loglevel` arg to `DEBUG`, you should be able to see something like `Client <your ip> request dump: <webhook payload>`. Sanitise it and post it here. If you need any help or get stuck, don't forget to ask; it just might take some time for me to reply.

**Comment by EricH9958** [comment]
Here is a debug log with On Grab and On Release Import enabled in the webhook. 
[autoscan.log](https://github.com/NiNiyas/autoscan/files/13228975/autoscan.log)

**Comment by NiNiyas** [comment]
Looking at the log files, scan finishes successfully. You only need `On Release Import`  and `On Upgrade` trigger. I'll update the readme with the updated trigger names.

**Comment by EricH9958** [comment]
Here's a screencap for the documentation.

![2023-11-01 15_42_19-Connect Settings - Lidarr](https://github.com/NiNiyas/autoscan/assets/29580743/a443f981-c076-4e41-90a5-42d2854f232f)

**Comment by NiNiyas** [comment]
Thanks so much!
